### ISSUE TITLE
opcap fails when using OpenShift 4.10.19

### ISSUE THREAD

**Issue by mrhillsman** [opdev/opcap#80]
First run (clean cluster)

Melvins-MacBook-Pro:opcap mrhillsman$ export KUBECONFIG=/Users/mrhillsman/Downloads/opcap-4-10-7fs66-kubeconfig.yaml                                                  [15/15]
Melvins-MacBook-Pro:opcap mrhillsman$ go run main.go check
I0624 14:23:56.830139   41294 request.go:601] Waited for 1.049759232s due to client-side throttling, not priority and fairness, request: GET:https://api.opcap-4-10-7fs66.opd
ev.io:6443/apis/oauth.openshift.io/v1?timeout=32s
check called
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x380 pc=0x20c2719]

goroutine 1 [running]:
opcap/internal/operator.operatorClient.WaitForCsvOnNamespace({{0x271d130?, 0xc000199500?}}, {0xc000040c00, 0x1d})
        /Users/mrhillsman/Development/goland/opcap/internal/operator/csv.go:59 +0x2f9
opcap/internal/capability.OperatorInstall({{0xc00110dbf0, 0x2b}, {0xc0009e6808, 0x6}, {0x249731f, 0x13}, {0x249a60a, 0x15}, {0xc0009d89c0, 0x17}, ...}, ...)
        /Users/mrhillsman/Development/goland/opcap/internal/capability/operator_install.go:122 +0xdb2
opcap/internal/capability.OperatorInstallAllFromCatalog({0x249731f, 0x13}, {0x249a60a?, 0x1?})
        /Users/mrhillsman/Development/goland/opcap/internal/capability/operator_install.go:38 +0x298                                                                         opcap/cmd.glob..func1(0x330e020?, {0x2483f77?, 0x0?, 0x0?})
        /Users/mrhillsman/Development/goland/opcap/cmd/check.go:31 +0x73
github.com/spf13/cobra.(*Command).execute(0x330e020, {0x3359130, 0x0, 0x0})
        /Users/mrhillsman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x330e2a0)
        /Users/mrhillsman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/mrhillsman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
opcap/cmd.Execute()
        /Users/mrhillsman/Development/goland/opcap/cmd/root.go:35 +0x25
main.main()
        /Users/mrhillsman/Development/goland/opcap/main.go:10 +0x17
exit status 2

Second run (same cluster after first run failed)

Melvins-MacBook-Pro:opcap mrhillsman$ go run main.go check
I0624 15:34:47.433976   41537 request.go:601] Waited for 1.000852004s due to client-side throttling, not priority and fairness, request: GET:https://api.opcap-4-10-7fs66.opd
ev.io:6443/apis/admissionregistration.k8s.io/v1?timeout=32s
check called
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x380 pc=0x20c2719]

goroutine 1 [running]:
opcap/internal/operator.operatorClient.WaitForCsvOnNamespace({{0x271d130?, 0xc0001903f0?}}, {0xc0009d6a80, 0x12})
        /Users/mrhillsman/Development/goland/opcap/internal/operator/csv.go:59 +0x2f9
opcap/internal/capability.OperatorInstall({{0xc0010a2ba0, 0x20}, {0xc0002ef9e8, 0x6}, {0x249731f, 0x13}, {0x249a60a, 0x15}, {0xc0002ef510, 0xc}, ...}, ...)
        /Users/mrhillsman/Development/goland/opcap/internal/capability/operator_install.go:122 +0xdb2
opcap/internal/capability.OperatorInstallAllFromCatalog({0x249731f, 0x13}, {0x249a60a?, 0x1?})
        /Users/mrhillsman/Development/goland/opcap/internal/capability/operator_install.go:38 +0x298                                                                         opcap/cmd.glob..func1(0x330e020?, {0x2483f77?, 0x0?, 0x0?})
        /Users/mrhillsman/Development/goland/opcap/cmd/check.go:31 +0x73
github.com/spf13/cobra.(*Command).execute(0x330e020, {0x3359130, 0x0, 0x0})
        /Users/mrhillsman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x330e2a0)
        /Users/mrhillsman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/mrhillsman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
opcap/cmd.Execute()
        /Users/mrhillsman/Development/goland/opcap/cmd/root.go:35 +0x25
main.main()
        /Users/mrhillsman/Development/goland/opcap/main.go:10 +0x17
exit status 2

**Comment by mrhillsman** [comment]
SNO still available for now if required for troubleshooting:

https://console-openshift-console.apps.opcap-4-10-7fs66.opdev.io/

https://console-openshift-console.apps.eng.opdev.io/k8s/ns/opcap-4-10-7fs66/secrets/opcap-4-10-7fs66-0-5v4mz-admin-password

https://console-openshift-console.apps.eng.opdev.io/k8s/ns/opcap-4-10-7fs66/secrets/opcap-4-10-7fs66-0-5v4mz-admin-kubeconfig

**Comment by mrhillsman** [comment]
Looks like this was an issue with the cluster or network issue during the test.
